### ISSUE TITLE
Some doubts about DE_function

### ISSUE THREAD

**Issue by XUEbaogai0101** [XZouProjects/scCODE#1]
Hi Dr.Zou,
 I had run an example on scCODE, but I am confused about the 'Detected_times'. I mean, the results were ordered by the 'Detected_times', so the top of the results contained all counts of DE methods, such as 5. But for the next ordered genes of the results, their 'Detected_times' were 4, then how could I know which method was contained in these ordered genes? 
Thank you very much!
XUE

**Comment by XUEbaogai0101** [comment]
Besides, forgives my ignorance, could you tell me how to explain the results of 'Z-score-metrics'?
> edgeR     limma     DESeq2 wilcox_test       BPSC    t_test
conquer 0.4944310 1.7003058 -0.2292351   0.2075869  0.6584251 1.6743097
scmap   0.4396737 0.8297328 -5.5151454  -0.9313029 -0.1625449 0.8337633

**Comment by XZouProjects** [comment]
Hi XUE,

Glad you are interested in our work. Since scCODE would select the appropriate method firstly (default by Top_5), the DE results detected by these methods should be considered reliable.
Then, the order by the “Detected times” is made by scCODE as a suggestion. Your concern about the information of the method by which the genes were detected is reasonable. We would provide this information in the coming update, soon.

Best

Xin Zou





发自我的iPhone

在 2022年5月5日，下午5:23，XUEbaogai0101 ***@***.***> 写道：

﻿

Besides, forgives my ignorance, could you tell me how to explain the results of 'Z-score-metrics'?

edgeR limma DESeq2 wilcox_test BPSC t_test
conquer 0.4944310 1.7003058 -0.2292351 0.2075869 0.6584251 1.6743097
scmap 0.4396737 0.8297328 -5.5151454 -0.9313029 -0.1625449 0.8337633

**Comment by XUEbaogai0101** [comment]
Hi, Dr.Zou! Thanks for your generous answer. I wish you success in your work.

**Comment by XZouProjects** [comment]
Hi

The algorithm is going to be published on Briefings in bioinformatics. Please refer to the paper.

Thanks

Xin

发自我的iPhone

在 2022年5月6日，下午2:40，XUEbaogai0101 ***@***.***> 写道：

﻿

Closed #1<https://github.com/XZouProjects/scCODE/issues/1>.

**Comment by XUEbaogai0101** [comment]
Yes, of course.
I can't wait to see your publication. It's my pleasure to quote your algorithm.
Cheer!

**Comment by XZouProjects** [comment]
This unformated final version, hope it is helpful.

Best

Xin

________________________________
